library(analogsea)
library(ssh)
Sys.setenv(DO_PAT="eae4166ed2fac0e3c41660fe26a009bb0176ab8bceeaf753faf5189f58a06520")
temp <- analogsea::droplets()
server <- temp$`shiny-server`
droplet_ssh(server, "rm /srv/shiny-server/cciss_spatial/app.R")
droplet_ssh(server, "rm /srv/shiny-server/cciss_spatial/plot_functions.R")

droplet_upload(server, "./spatial_testing/app.R", "/srv/shiny-server/spatial_test/app.R")
droplet_ssh(server, "systemctl restart shiny-server")
#
#
#droplet_ssh(server, "mv /srv/shiny-server/spatial_test/cciss_db.sqlite /srv/shiny-server/")
setwd("./spatial_testing/")
analogsea::droplet_ssh(server,"rm -R /srv/shiny-server/cciss_spatial")
analogsea::droplet_ssh(server, "mkdir /srv/shiny-server/cciss_spatial")
analogsea::droplet_upload(server, "./app.R", "/srv/shiny-server/cciss_spatial/app.R")
analogsea::droplet_upload(server, "../.Renviron", "/srv/shiny-server/cciss_spatial/.Renviron")
analogsea::droplet_upload(server, "./JS_Source.R", "/srv/shiny-server/cciss_spatial/JS_Source.R")
analogsea::droplet_upload(server, "./plot_functions.R", "/srv/shiny-server/cciss_spatial/")
analogsea::droplet_upload(server, "./subzone_cols.csv", "/srv/shiny-server/cciss_spatial/subzone_cols.csv")
analogsea::droplet_upload(server, "./WNAv13_ZoneCols.csv", "/srv/shiny-server/cciss_spatial/")
analogsea::droplet_upload(server, "./htmlwidgets", "/srv/shiny-server/cciss_spatial")
analogsea::droplet_upload(server, "./Raster_Templated.tif", "/srv/shiny-server/cciss_spatial")
analogsea::droplet_upload(server, "./www", "/srv/shiny-server/cciss_spatial")
analogsea::droplet_upload(server, "./district_bounds.csv", "/srv/shiny-server/cciss_spatial")
analogsea::droplet_ssh(server, "chown -R shiny:shiny /srv/shiny-server")
analogsea::droplet_ssh(server, "systemctl restart shiny-server")
